name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Check commands if works
      run: |
        id
        sudo id
        sudo apt-get -y update
        sudo apt install virtualbox
        sudo apt install vagrant
        vagrant --version
        vagrant init centos/7
        vagrant up
        vagrant destroy -f
  
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Initial run of ansible test
      run: |
        ansible-playbook -i tests/hosts tests/test-default.yml
