name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Check simple settings
      run: |
        id
        sudo id
        free
        df -h
        lscpu
        ps -eaf
        sudo iptables -nvL
    - name: Check commands if works
      run: |
        sudo apt-get -y update
        sudo apt install virtualbox
        sudo apt install vagrant
        vagrant --version
        vagrant plugin install vagrant-vbguest
        # NOTE: So far this was working fine - however following commands ended with timeout (had to cancel)
        # vagrant up
        # vagrant destroy -f
  
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Initial run of ansible test
      run: |
        ansible-playbook -i tests/hosts tests/test-default.yml
