name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Check simple settings
      run: |
        id
        sudo id
        free
        df -h
        lscpu
        ps -eaf
        sudo iptables -nvL
        ls -la
        pwd
    - name: Apt-get Update packages
      run: sudo apt-get -y update
    - name: Apt-get Install required software
      run: sudo apt-get -y install virtualbox vagrant
    - name: Start vagrant
      run: |
        vagrant --version
        # NOTE: So far this was working fine - however following commands ended with timeout (had to cancel)
        # vagrant plugin install vagrant-vbguest
        vagrant up
        vagrant status
        vagrant destroy -f
  
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Initial run of ansible test
      run: |
        ansible-playbook -i tests/hosts tests/test-default.yml
